#!/bin/sh
case "$1" in
  start)
    echo "Loading LDD modules"
    insmod /lib/modules/*/extra/scull.ko
    insmod /lib/modules/*/extra/faulty.ko
    modprobe hello

    echo "Creating scull device nodes"
    scull_major=$(cat /proc/devices | grep scull | awk '{print $1}')
    [ -n "$scull_major" ] && {
      mknod /dev/scull0 c $scull_major 0
      mknod /dev/scull1 c $scull_major 1
      mknod /dev/scull2 c $scull_major 2
      mknod /dev/scull3 c $scull_major 3
    }

    echo "Creating faulty device node"
    faulty_major=$(cat /proc/devices | grep faulty | awk '{print $1}')
    [ -n "$faulty_major" ] && mknod /dev/faulty c $faulty_major 0
    ;;

  stop)
    echo "Unloading LDD modules"
    rm -f /dev/scull* /dev/faulty
    rmmod hello
    rmmod faulty
    rmmod scull
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
